In [6]:
import bruker_converter as bc
import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt
import sys

In [5]:
hd = bc.read_bruker_header_file('/mnt/c/Users/adamb/Desktop/ratcogsample/DTI.D75/10/pdata/1/visu_pars')

In [6]:
offset = bc.get_offset(hd)
print offset

[ 15.66729428 -11.88605864  25.        ]


In [7]:
res = bc.get_resolution(hd)
print res

[ 0.15  0.15  0.15]


In [8]:
matrix = bc.get_matrix(hd)
print matrix

(192, 256, 128)


In [9]:
affine = bc.get_affine(hd)
print affine

[[ -1.49634600e-01  -1.04634697e-02  -9.16217424e-18  -1.73730412e+01]
 [  1.04634697e-02  -1.49634600e-01   6.40681628e-19  -2.38462048e+01]
 [ -9.18454699e-18   1.02407575e-25   1.50000006e-01  -1.18860588e+01]
 [ -0.00000000e+00  -0.00000000e+00  -0.00000000e+00   1.00000000e+00]]


In [10]:
x = np.fromfile('/mnt/c/Users/adamb/Desktop/ratcogsample/DTI.D75/10/pdata/1/2dseq', dtype=np.int16)
x.byteswap(False)
x = np.reshape(x,matrix, order='F')

IndexError: too many indices for array

In [11]:
img = nib.Nifti1Image(x, affine)
img.qoffset_x = offset[0]
img.qoffset_y = offset[2]
img.qoffset_z = offset[1]
img.affine[0:3,3] = [offset[0], offset[2], offset[1]]
img.qform_code = 'scanner'
img.sform_code = 'scanner'
nib.save(img, 'test.nii')

In [7]:
import file_finder

In [11]:
files2seq = file_finder.scan_for_files('2dseq', '/mnt/c/Users/adamb/Desktop/ratcogsample', [])
filesmethod = file_finder.scan_for_files('method', '/mnt/c/Users/adamb/Desktop/ratcogsample', [])
filesvisupars = file_finder.scan_for_files('visu_pars', '/mnt/c/Users/adamb/Desktop/ratcogsample', [])

In [22]:
print files2seq[0].split('/')[-4]
print filesmethod[0][:-6]
print filesvisupars[0][:-17]

1
/mnt/c/Users/adamb/Desktop/ratcogsample/DTI.D74/1/
/mnt/c/Users/adamb/Desktop/ratcogsample/DTI.D74/1/


In [31]:
hd = bc.read_bruker_header_file('/mnt/c/Users/adamb/Desktop/ratcogsample/DTI.D82/8/pdata/1/visu_pars')

In [32]:
print hd['VisuStudyId'][0]

rat_cog_10152-1


In [33]:
print hd['VisuAcquisitionProtocol']

['RatBrain_EPIDTI_64dirs_RPE']


In [34]:
'RPE' in hd['VisuAcquisitionProtocol'][0]

True

In [27]:
print ('PVM_DwEffBval' in hd)

True
